replicaCount: 1

image:
  repository: aravind310730/my-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}